CREATE TABLE IF NOT EXISTS system_errors (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    code VARCHAR(32) NOT NULL,
    fingerprint CHAR(64) NOT NULL,
    source VARCHAR(20) NOT NULL,
    severity VARCHAR(20) NOT NULL DEFAULT 'medium',
    status VARCHAR(24) NOT NULL DEFAULT 'new',
    company_id BIGINT NULL,
    actor_type VARCHAR(20) NULL,
    actor_id BIGINT NULL,
    module VARCHAR(80) NOT NULL,
    error_type VARCHAR(120) NOT NULL,
    message VARCHAR(1000) NOT NULL,
    route VARCHAR(500) NULL,
    request_method VARCHAR(12) NULL,
    occurrence_count INT UNSIGNED NOT NULL DEFAULT 1,
    support_ticket_id BIGINT NULL,
    first_occurred_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_occurred_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_at DATETIME NULL,
    resolved_by BIGINT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_system_error_code (code),
    UNIQUE KEY uq_system_error_fingerprint (fingerprint),
    INDEX idx_system_error_status_severity (status, severity, last_occurred_at),
    INDEX idx_system_error_company (company_id, last_occurred_at),
    INDEX idx_system_error_module (module, last_occurred_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS system_error_occurrences (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    error_id BIGINT NOT NULL,
    company_id BIGINT NULL,
    actor_type VARCHAR(20) NULL,
    actor_id BIGINT NULL,
    route VARCHAR(500) NULL,
    request_method VARCHAR(12) NULL,
    page_url VARCHAR(500) NULL,
    browser_summary VARCHAR(300) NULL,
    technical_summary VARCHAR(1500) NULL,
    occurred_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_error_occurrence_error (error_id, occurred_at),
    INDEX idx_error_occurrence_company (company_id, occurred_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
